USING "types.sch"

#IF FEATURE_GEN9_STANDALONE

// Corresponds to LandingPageConfig::eEntryPoint
ENUM LANDING_PAGE_ENTRYPOINT
	ENTRYPOINT_MODE_SELECT = 1,
	ENTRYPOINT_SINGLEPLAYER_MIGRATION = 2,
	ENTRYPOINT_MULTIPLAYER_REVIEW_CHARACTERS = 3,
	ENTRYPOINT_MULTIPLAYER_MIGRATE_CHARACTER = 4,
	// ENTRYPOINT_MULTIPLAYER_MIGRATION_ERROR_IN_PROGRESS = 5,
	// ENTRYPOINT_MULTIPLAYER_MIGRATION_ERROR_UNKNOWN = 6,
	ENTRYPOINT_STORYMODE_UPSELL = 7,
	ENTRYPOINT_WINDFALL = 8,
	
	// ENTRYPOINT_SRL_ERROR_ENTITLEMENTS = 9,
	// ENTRYPOINT_SRL_ERROR_GENERIC = 10,
	// ENTRYPOINT_INVITE_ERROR_GENERIC = 11,
	ENTRYPOINT_COUNT = 12
ENDENUM

//INFO: 
//PARAM NOTES:
//PURPOSE: Return whether the Landing Page is currently active
NATIVE FUNC BOOL IS_LANDING_PAGE_ACTIVE() = "0xdcc443647e72d3a9"

//INFO: 
//PARAM NOTES: entrypointId - Where the Landing Page should launch to
//PURPOSE: Launch the landing page
NATIVE PROC SET_SHOULD_LAUNCH_LANDING_PAGE(LANDING_PAGE_ENTRYPOINT entrypointId) = "0x84170bb1a4049cce"

//INFO: 
//PARAM NOTES:
//PURPOSE: Dismiss the landing page
NATIVE PROC SET_SHOULD_DISMISS_LANDING_PAGE() = "0x586d714afa1a4068"

//INFO: 
//PARAM NOTES:
//PURPOSE: Return the character slot selection made on the landing page. Will return -1 if no selection was made
NATIVE FUNC INT GET_LANDING_PAGE_SELECTED_CHARACTER_SLOT() = "0xfb9d4edbe2e05b3f"

#ENDIF // FEATURE_GEN9_STANDALONE
